//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATX_POS.DataCompanyNAV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataCompany_Binding", Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public partial class DataCompany_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataCompany_Service() {
            this.Url = global::ATX_POS.Properties.Settings.Default.ATX_POS_DataCompanyNAV_DataCompany_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/datacompany:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/datacompany", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/datacompany", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DataCompany")]
        public DataCompany ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((DataCompany)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/datacompany:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/datacompany", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/datacompany", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DataCompany[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] DataCompany_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((DataCompany[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(DataCompany_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(DataCompany_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/datacompany:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/datacompany", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/datacompany", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/datacompany:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/datacompany", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/datacompany", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/datacompany:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/datacompany", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/datacompany", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref DataCompany DataCompany) {
            object[] results = this.Invoke("Update", new object[] {
                        DataCompany});
            DataCompany = ((DataCompany)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(DataCompany DataCompany) {
            this.UpdateAsync(DataCompany, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(DataCompany DataCompany, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        DataCompany}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/datacompany:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/datacompany", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/datacompany", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref DataCompany[] DataCompany_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        DataCompany_List});
            DataCompany_List = ((DataCompany[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(DataCompany[] DataCompany_List) {
            this.UpdateMultipleAsync(DataCompany_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(DataCompany[] DataCompany_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        DataCompany_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public partial class DataCompany {
        
        private string keyField;
        
        private string nameField;
        
        private string name_2Field;
        
        private string addressField;
        
        private string address_2Field;
        
        private string cityField;
        
        private string countyField;
        
        private string post_CodeField;
        
        private string country_Region_CodeField;
        
        private string phone_NoField;
        
        private string federal_ID_NoField;
        
        private string industrial_ClassificationField;
        
        private string external_Address_NumberField;
        
        private string regimen_FiscalField;
        
        private string fax_NoField;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string iC_Partner_CodeField;
        
        private IC_Inbox_Type iC_Inbox_TypeField;
        
        private bool iC_Inbox_TypeFieldSpecified;
        
        private string iC_Inbox_DetailsField;
        
        private string bank_NameField;
        
        private string bank_Branch_NoField;
        
        private string bank_Account_NoField;
        
        private string payment_Routing_NoField;
        
        private string giro_NoField;
        
        private string sWIFT_CodeField;
        
        private string iBANField;
        
        private string uS_Country_Region_CodeField;
        
        private string canada_Country_Region_CodeField;
        
        private string mexico_Country_Region_CodeField;
        
        private string ship_to_NameField;
        
        private string ship_to_AddressField;
        
        private string ship_to_Address_2Field;
        
        private string ship_to_CityField;
        
        private string ship_to_CountyField;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_Country_Region_CodeField;
        
        private string ship_to_ContactField;
        
        private string ship_to_UPS_ZoneField;
        
        private string location_CodeField;
        
        private string responsibility_CenterField;
        
        private string check_Avail_Period_CalcField;
        
        private Check_Avail_Time_Bucket check_Avail_Time_BucketField;
        
        private bool check_Avail_Time_BucketFieldSpecified;
        
        private string base_Calendar_CodeField;
        
        private string customized_CalendarField;
        
        private string cal_Convergence_Time_FrameField;
        
        private string vAT_Registration_NoField;
        
        private string qST_Registration_NoField;
        
        private string tax_Area_CodeField;
        
        private string tax_Exemption_NoField;
        
        private string tax_SchemeField;
        
        private string provincial_Tax_Area_CodeField;
        
        private string rFC_NoField;
        
        private string cURP_NoField;
        
        private string state_InscriptionField;
        
        private string software_Identification_CodeField;
        
        private string gLNField;
        
        private bool allow_Blank_Payment_InfoField;
        
        private bool allow_Blank_Payment_InfoFieldSpecified;
        
        private System_Indicator system_IndicatorField;
        
        private bool system_IndicatorFieldSpecified;
        
        private System_Indicator_Style system_Indicator_StyleField;
        
        private bool system_Indicator_StyleFieldSpecified;
        
        private string system_Indicator_TextField;
        
        /// <comentarios/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        public string Name_2 {
            get {
                return this.name_2Field;
            }
            set {
                this.name_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <comentarios/>
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <comentarios/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <comentarios/>
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Federal_ID_No {
            get {
                return this.federal_ID_NoField;
            }
            set {
                this.federal_ID_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Industrial_Classification {
            get {
                return this.industrial_ClassificationField;
            }
            set {
                this.industrial_ClassificationField = value;
            }
        }
        
        /// <comentarios/>
        public string External_Address_Number {
            get {
                return this.external_Address_NumberField;
            }
            set {
                this.external_Address_NumberField = value;
            }
        }
        
        /// <comentarios/>
        public string Regimen_Fiscal {
            get {
                return this.regimen_FiscalField;
            }
            set {
                this.regimen_FiscalField = value;
            }
        }
        
        /// <comentarios/>
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
            }
        }
        
        /// <comentarios/>
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
            }
        }
        
        /// <comentarios/>
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public IC_Inbox_Type IC_Inbox_Type {
            get {
                return this.iC_Inbox_TypeField;
            }
            set {
                this.iC_Inbox_TypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IC_Inbox_TypeSpecified {
            get {
                return this.iC_Inbox_TypeFieldSpecified;
            }
            set {
                this.iC_Inbox_TypeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string IC_Inbox_Details {
            get {
                return this.iC_Inbox_DetailsField;
            }
            set {
                this.iC_Inbox_DetailsField = value;
            }
        }
        
        /// <comentarios/>
        public string Bank_Name {
            get {
                return this.bank_NameField;
            }
            set {
                this.bank_NameField = value;
            }
        }
        
        /// <comentarios/>
        public string Bank_Branch_No {
            get {
                return this.bank_Branch_NoField;
            }
            set {
                this.bank_Branch_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Bank_Account_No {
            get {
                return this.bank_Account_NoField;
            }
            set {
                this.bank_Account_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Payment_Routing_No {
            get {
                return this.payment_Routing_NoField;
            }
            set {
                this.payment_Routing_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Giro_No {
            get {
                return this.giro_NoField;
            }
            set {
                this.giro_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string SWIFT_Code {
            get {
                return this.sWIFT_CodeField;
            }
            set {
                this.sWIFT_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <comentarios/>
        public string US_Country_Region_Code {
            get {
                return this.uS_Country_Region_CodeField;
            }
            set {
                this.uS_Country_Region_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Canada_Country_Region_Code {
            get {
                return this.canada_Country_Region_CodeField;
            }
            set {
                this.canada_Country_Region_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Mexico_Country_Region_Code {
            get {
                return this.mexico_Country_Region_CodeField;
            }
            set {
                this.mexico_Country_Region_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_Name {
            get {
                return this.ship_to_NameField;
            }
            set {
                this.ship_to_NameField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_Address {
            get {
                return this.ship_to_AddressField;
            }
            set {
                this.ship_to_AddressField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_Address_2 {
            get {
                return this.ship_to_Address_2Field;
            }
            set {
                this.ship_to_Address_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_City {
            get {
                return this.ship_to_CityField;
            }
            set {
                this.ship_to_CityField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_County {
            get {
                return this.ship_to_CountyField;
            }
            set {
                this.ship_to_CountyField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_Post_Code {
            get {
                return this.ship_to_Post_CodeField;
            }
            set {
                this.ship_to_Post_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_Country_Region_Code {
            get {
                return this.ship_to_Country_Region_CodeField;
            }
            set {
                this.ship_to_Country_Region_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_Contact {
            get {
                return this.ship_to_ContactField;
            }
            set {
                this.ship_to_ContactField = value;
            }
        }
        
        /// <comentarios/>
        public string Ship_to_UPS_Zone {
            get {
                return this.ship_to_UPS_ZoneField;
            }
            set {
                this.ship_to_UPS_ZoneField = value;
            }
        }
        
        /// <comentarios/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <comentarios/>
        public string Check_Avail_Period_Calc {
            get {
                return this.check_Avail_Period_CalcField;
            }
            set {
                this.check_Avail_Period_CalcField = value;
            }
        }
        
        /// <comentarios/>
        public Check_Avail_Time_Bucket Check_Avail_Time_Bucket {
            get {
                return this.check_Avail_Time_BucketField;
            }
            set {
                this.check_Avail_Time_BucketField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Check_Avail_Time_BucketSpecified {
            get {
                return this.check_Avail_Time_BucketFieldSpecified;
            }
            set {
                this.check_Avail_Time_BucketFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Customized_Calendar {
            get {
                return this.customized_CalendarField;
            }
            set {
                this.customized_CalendarField = value;
            }
        }
        
        /// <comentarios/>
        public string Cal_Convergence_Time_Frame {
            get {
                return this.cal_Convergence_Time_FrameField;
            }
            set {
                this.cal_Convergence_Time_FrameField = value;
            }
        }
        
        /// <comentarios/>
        public string VAT_Registration_No {
            get {
                return this.vAT_Registration_NoField;
            }
            set {
                this.vAT_Registration_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string QST_Registration_No {
            get {
                return this.qST_Registration_NoField;
            }
            set {
                this.qST_Registration_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Tax_Area_Code {
            get {
                return this.tax_Area_CodeField;
            }
            set {
                this.tax_Area_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Tax_Exemption_No {
            get {
                return this.tax_Exemption_NoField;
            }
            set {
                this.tax_Exemption_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Tax_Scheme {
            get {
                return this.tax_SchemeField;
            }
            set {
                this.tax_SchemeField = value;
            }
        }
        
        /// <comentarios/>
        public string Provincial_Tax_Area_Code {
            get {
                return this.provincial_Tax_Area_CodeField;
            }
            set {
                this.provincial_Tax_Area_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string RFC_No {
            get {
                return this.rFC_NoField;
            }
            set {
                this.rFC_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string CURP_No {
            get {
                return this.cURP_NoField;
            }
            set {
                this.cURP_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string State_Inscription {
            get {
                return this.state_InscriptionField;
            }
            set {
                this.state_InscriptionField = value;
            }
        }
        
        /// <comentarios/>
        public string Software_Identification_Code {
            get {
                return this.software_Identification_CodeField;
            }
            set {
                this.software_Identification_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
            }
        }
        
        /// <comentarios/>
        public bool Allow_Blank_Payment_Info {
            get {
                return this.allow_Blank_Payment_InfoField;
            }
            set {
                this.allow_Blank_Payment_InfoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Blank_Payment_InfoSpecified {
            get {
                return this.allow_Blank_Payment_InfoFieldSpecified;
            }
            set {
                this.allow_Blank_Payment_InfoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public System_Indicator System_Indicator {
            get {
                return this.system_IndicatorField;
            }
            set {
                this.system_IndicatorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool System_IndicatorSpecified {
            get {
                return this.system_IndicatorFieldSpecified;
            }
            set {
                this.system_IndicatorFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public System_Indicator_Style System_Indicator_Style {
            get {
                return this.system_Indicator_StyleField;
            }
            set {
                this.system_Indicator_StyleField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool System_Indicator_StyleSpecified {
            get {
                return this.system_Indicator_StyleFieldSpecified;
            }
            set {
                this.system_Indicator_StyleFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string System_Indicator_Text {
            get {
                return this.system_Indicator_TextField;
            }
            set {
                this.system_Indicator_TextField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public enum IC_Inbox_Type {
        
        /// <comentarios/>
        File_Location,
        
        /// <comentarios/>
        Database,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public enum Check_Avail_Time_Bucket {
        
        /// <comentarios/>
        Day,
        
        /// <comentarios/>
        Week,
        
        /// <comentarios/>
        Month,
        
        /// <comentarios/>
        Quarter,
        
        /// <comentarios/>
        Year,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public enum System_Indicator {
        
        /// <comentarios/>
        None,
        
        /// <comentarios/>
        Custom_Text,
        
        /// <comentarios/>
        Company_Information,
        
        /// <comentarios/>
        Company,
        
        /// <comentarios/>
        Database,
        
        /// <comentarios/>
        Company_x002B_Database,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public enum System_Indicator_Style {
        
        /// <comentarios/>
        Standard,
        
        /// <comentarios/>
        Accent1,
        
        /// <comentarios/>
        Accent2,
        
        /// <comentarios/>
        Accent3,
        
        /// <comentarios/>
        Accent4,
        
        /// <comentarios/>
        Accent5,
        
        /// <comentarios/>
        Accent6,
        
        /// <comentarios/>
        Accent7,
        
        /// <comentarios/>
        Accent8,
        
        /// <comentarios/>
        Accent9,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public partial class DataCompany_Filter {
        
        private DataCompany_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        public DataCompany_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <comentarios/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/datacompany")]
    public enum DataCompany_Fields {
        
        /// <comentarios/>
        Name,
        
        /// <comentarios/>
        Name_2,
        
        /// <comentarios/>
        Address,
        
        /// <comentarios/>
        Address_2,
        
        /// <comentarios/>
        City,
        
        /// <comentarios/>
        County,
        
        /// <comentarios/>
        Post_Code,
        
        /// <comentarios/>
        Country_Region_Code,
        
        /// <comentarios/>
        Phone_No,
        
        /// <comentarios/>
        Federal_ID_No,
        
        /// <comentarios/>
        Industrial_Classification,
        
        /// <comentarios/>
        External_Address_Number,
        
        /// <comentarios/>
        Regimen_Fiscal,
        
        /// <comentarios/>
        Fax_No,
        
        /// <comentarios/>
        E_Mail,
        
        /// <comentarios/>
        Home_Page,
        
        /// <comentarios/>
        IC_Partner_Code,
        
        /// <comentarios/>
        IC_Inbox_Type,
        
        /// <comentarios/>
        IC_Inbox_Details,
        
        /// <comentarios/>
        Bank_Name,
        
        /// <comentarios/>
        Bank_Branch_No,
        
        /// <comentarios/>
        Bank_Account_No,
        
        /// <comentarios/>
        Payment_Routing_No,
        
        /// <comentarios/>
        Giro_No,
        
        /// <comentarios/>
        SWIFT_Code,
        
        /// <comentarios/>
        IBAN,
        
        /// <comentarios/>
        US_Country_Region_Code,
        
        /// <comentarios/>
        Canada_Country_Region_Code,
        
        /// <comentarios/>
        Mexico_Country_Region_Code,
        
        /// <comentarios/>
        Ship_to_Name,
        
        /// <comentarios/>
        Ship_to_Address,
        
        /// <comentarios/>
        Ship_to_Address_2,
        
        /// <comentarios/>
        Ship_to_City,
        
        /// <comentarios/>
        Ship_to_County,
        
        /// <comentarios/>
        Ship_to_Post_Code,
        
        /// <comentarios/>
        Ship_to_Country_Region_Code,
        
        /// <comentarios/>
        Ship_to_Contact,
        
        /// <comentarios/>
        Ship_to_UPS_Zone,
        
        /// <comentarios/>
        Location_Code,
        
        /// <comentarios/>
        Responsibility_Center,
        
        /// <comentarios/>
        Check_Avail_Period_Calc,
        
        /// <comentarios/>
        Check_Avail_Time_Bucket,
        
        /// <comentarios/>
        Base_Calendar_Code,
        
        /// <comentarios/>
        Customized_Calendar,
        
        /// <comentarios/>
        Cal_Convergence_Time_Frame,
        
        /// <comentarios/>
        VAT_Registration_No,
        
        /// <comentarios/>
        QST_Registration_No,
        
        /// <comentarios/>
        Tax_Area_Code,
        
        /// <comentarios/>
        Tax_Exemption_No,
        
        /// <comentarios/>
        Tax_Scheme,
        
        /// <comentarios/>
        Provincial_Tax_Area_Code,
        
        /// <comentarios/>
        RFC_No,
        
        /// <comentarios/>
        CURP_No,
        
        /// <comentarios/>
        State_Inscription,
        
        /// <comentarios/>
        Software_Identification_Code,
        
        /// <comentarios/>
        GLN,
        
        /// <comentarios/>
        Allow_Blank_Payment_Info,
        
        /// <comentarios/>
        System_Indicator,
        
        /// <comentarios/>
        System_Indicator_Style,
        
        /// <comentarios/>
        System_Indicator_Text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataCompany Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataCompany)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataCompany[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataCompany[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataCompany DataCompany {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataCompany)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataCompany[] DataCompany_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataCompany[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591