//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATX_POS.DataBranchNAV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataBranch_Binding", Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public partial class DataBranch_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataBranch_Service() {
            this.Url = global::ATX_POS.Properties.Settings.Default.ATX_POS_DataBranchNAV_DataBranch_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DataBranch")]
        public DataBranch Read(string Code) {
            object[] results = this.Invoke("Read", new object[] {
                        Code});
            return ((DataBranch)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Code) {
            this.ReadAsync(Code, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Code, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Code}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DataBranch")]
        public DataBranch ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((DataBranch)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DataBranch[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] DataBranch_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((DataBranch[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(DataBranch_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(DataBranch_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref DataBranch DataBranch) {
            object[] results = this.Invoke("Create", new object[] {
                        DataBranch});
            DataBranch = ((DataBranch)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(DataBranch DataBranch) {
            this.CreateAsync(DataBranch, null);
        }
        
        /// <remarks/>
        public void CreateAsync(DataBranch DataBranch, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        DataBranch}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref DataBranch[] DataBranch_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        DataBranch_List});
            DataBranch_List = ((DataBranch[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(DataBranch[] DataBranch_List) {
            this.CreateMultipleAsync(DataBranch_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(DataBranch[] DataBranch_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        DataBranch_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref DataBranch DataBranch) {
            object[] results = this.Invoke("Update", new object[] {
                        DataBranch});
            DataBranch = ((DataBranch)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(DataBranch DataBranch) {
            this.UpdateAsync(DataBranch, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(DataBranch DataBranch, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        DataBranch}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref DataBranch[] DataBranch_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        DataBranch_List});
            DataBranch_List = ((DataBranch[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(DataBranch[] DataBranch_List) {
            this.UpdateMultipleAsync(DataBranch_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(DataBranch[] DataBranch_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        DataBranch_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/databranch:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/databranch", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/databranch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public partial class DataBranch {
        
        private string keyField;
        
        private string codeField;
        
        private string nameField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string cityField;
        
        private string countyField;
        
        private string post_CodeField;
        
        private string country_Region_CodeField;
        
        private string contactField;
        
        private bool use_As_In_TransitField;
        
        private bool use_As_In_TransitFieldSpecified;
        
        private bool do_Not_Use_For_Tax_CalculationField;
        
        private bool do_Not_Use_For_Tax_CalculationFieldSpecified;
        
        private string tax_Area_CodeField;
        
        private string tax_Exemption_NoField;
        
        private string provincial_Tax_Area_CodeField;
        
        private string phone_NoField;
        
        private string fax_NoField;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private bool require_ReceiveField;
        
        private bool require_ReceiveFieldSpecified;
        
        private bool require_ShipmentField;
        
        private bool require_ShipmentFieldSpecified;
        
        private bool require_Put_awayField;
        
        private bool require_Put_awayFieldSpecified;
        
        private bool use_Put_away_WorksheetField;
        
        private bool use_Put_away_WorksheetFieldSpecified;
        
        private bool require_PickField;
        
        private bool require_PickFieldSpecified;
        
        private bool bin_MandatoryField;
        
        private bool bin_MandatoryFieldSpecified;
        
        private bool directed_Put_away_and_PickField;
        
        private bool directed_Put_away_and_PickFieldSpecified;
        
        private bool use_ADCSField;
        
        private bool use_ADCSFieldSpecified;
        
        private Default_Bin_Selection default_Bin_SelectionField;
        
        private bool default_Bin_SelectionFieldSpecified;
        
        private string outbound_Whse_Handling_TimeField;
        
        private string inbound_Whse_Handling_TimeField;
        
        private string base_Calendar_CodeField;
        
        private string customized_CalendarField;
        
        private bool use_Cross_DockingField;
        
        private bool use_Cross_DockingFieldSpecified;
        
        private string cross_Dock_Due_Date_CalcField;
        
        private string receipt_Bin_CodeField;
        
        private string shipment_Bin_CodeField;
        
        private string open_Shop_Floor_Bin_CodeField;
        
        private string to_Production_Bin_CodeField;
        
        private string from_Production_Bin_CodeField;
        
        private string adjustment_Bin_CodeField;
        
        private string cross_Dock_Bin_CodeField;
        
        private string to_Assembly_Bin_CodeField;
        
        private string from_Assembly_Bin_CodeField;
        
        private string asm_to_Order_Shpt_Bin_CodeField;
        
        private Special_Equipment special_EquipmentField;
        
        private bool special_EquipmentFieldSpecified;
        
        private Bin_Capacity_Policy bin_Capacity_PolicyField;
        
        private bool bin_Capacity_PolicyFieldSpecified;
        
        private bool allow_BreakbulkField;
        
        private bool allow_BreakbulkFieldSpecified;
        
        private string put_away_Template_CodeField;
        
        private bool always_Create_Put_away_LineField;
        
        private bool always_Create_Put_away_LineFieldSpecified;
        
        private bool always_Create_Pick_LineField;
        
        private bool always_Create_Pick_LineFieldSpecified;
        
        private bool pick_According_to_FEFOField;
        
        private bool pick_According_to_FEFOFieldSpecified;
        
        /// <comentarios/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <comentarios/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <comentarios/>
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
            }
        }
        
        /// <comentarios/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <comentarios/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <comentarios/>
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <comentarios/>
        public bool Use_As_In_Transit {
            get {
                return this.use_As_In_TransitField;
            }
            set {
                this.use_As_In_TransitField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_As_In_TransitSpecified {
            get {
                return this.use_As_In_TransitFieldSpecified;
            }
            set {
                this.use_As_In_TransitFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Do_Not_Use_For_Tax_Calculation {
            get {
                return this.do_Not_Use_For_Tax_CalculationField;
            }
            set {
                this.do_Not_Use_For_Tax_CalculationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Do_Not_Use_For_Tax_CalculationSpecified {
            get {
                return this.do_Not_Use_For_Tax_CalculationFieldSpecified;
            }
            set {
                this.do_Not_Use_For_Tax_CalculationFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Tax_Area_Code {
            get {
                return this.tax_Area_CodeField;
            }
            set {
                this.tax_Area_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Tax_Exemption_No {
            get {
                return this.tax_Exemption_NoField;
            }
            set {
                this.tax_Exemption_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Provincial_Tax_Area_Code {
            get {
                return this.provincial_Tax_Area_CodeField;
            }
            set {
                this.provincial_Tax_Area_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
            }
        }
        
        /// <comentarios/>
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
            }
        }
        
        /// <comentarios/>
        public bool Require_Receive {
            get {
                return this.require_ReceiveField;
            }
            set {
                this.require_ReceiveField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Require_ReceiveSpecified {
            get {
                return this.require_ReceiveFieldSpecified;
            }
            set {
                this.require_ReceiveFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Require_Shipment {
            get {
                return this.require_ShipmentField;
            }
            set {
                this.require_ShipmentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Require_ShipmentSpecified {
            get {
                return this.require_ShipmentFieldSpecified;
            }
            set {
                this.require_ShipmentFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Require_Put_away {
            get {
                return this.require_Put_awayField;
            }
            set {
                this.require_Put_awayField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Require_Put_awaySpecified {
            get {
                return this.require_Put_awayFieldSpecified;
            }
            set {
                this.require_Put_awayFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Use_Put_away_Worksheet {
            get {
                return this.use_Put_away_WorksheetField;
            }
            set {
                this.use_Put_away_WorksheetField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Put_away_WorksheetSpecified {
            get {
                return this.use_Put_away_WorksheetFieldSpecified;
            }
            set {
                this.use_Put_away_WorksheetFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Require_Pick {
            get {
                return this.require_PickField;
            }
            set {
                this.require_PickField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Require_PickSpecified {
            get {
                return this.require_PickFieldSpecified;
            }
            set {
                this.require_PickFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Bin_Mandatory {
            get {
                return this.bin_MandatoryField;
            }
            set {
                this.bin_MandatoryField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bin_MandatorySpecified {
            get {
                return this.bin_MandatoryFieldSpecified;
            }
            set {
                this.bin_MandatoryFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Directed_Put_away_and_Pick {
            get {
                return this.directed_Put_away_and_PickField;
            }
            set {
                this.directed_Put_away_and_PickField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Directed_Put_away_and_PickSpecified {
            get {
                return this.directed_Put_away_and_PickFieldSpecified;
            }
            set {
                this.directed_Put_away_and_PickFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Use_ADCS {
            get {
                return this.use_ADCSField;
            }
            set {
                this.use_ADCSField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_ADCSSpecified {
            get {
                return this.use_ADCSFieldSpecified;
            }
            set {
                this.use_ADCSFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public Default_Bin_Selection Default_Bin_Selection {
            get {
                return this.default_Bin_SelectionField;
            }
            set {
                this.default_Bin_SelectionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Default_Bin_SelectionSpecified {
            get {
                return this.default_Bin_SelectionFieldSpecified;
            }
            set {
                this.default_Bin_SelectionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Outbound_Whse_Handling_Time {
            get {
                return this.outbound_Whse_Handling_TimeField;
            }
            set {
                this.outbound_Whse_Handling_TimeField = value;
            }
        }
        
        /// <comentarios/>
        public string Inbound_Whse_Handling_Time {
            get {
                return this.inbound_Whse_Handling_TimeField;
            }
            set {
                this.inbound_Whse_Handling_TimeField = value;
            }
        }
        
        /// <comentarios/>
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Customized_Calendar {
            get {
                return this.customized_CalendarField;
            }
            set {
                this.customized_CalendarField = value;
            }
        }
        
        /// <comentarios/>
        public bool Use_Cross_Docking {
            get {
                return this.use_Cross_DockingField;
            }
            set {
                this.use_Cross_DockingField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Cross_DockingSpecified {
            get {
                return this.use_Cross_DockingFieldSpecified;
            }
            set {
                this.use_Cross_DockingFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Cross_Dock_Due_Date_Calc {
            get {
                return this.cross_Dock_Due_Date_CalcField;
            }
            set {
                this.cross_Dock_Due_Date_CalcField = value;
            }
        }
        
        /// <comentarios/>
        public string Receipt_Bin_Code {
            get {
                return this.receipt_Bin_CodeField;
            }
            set {
                this.receipt_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Shipment_Bin_Code {
            get {
                return this.shipment_Bin_CodeField;
            }
            set {
                this.shipment_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Open_Shop_Floor_Bin_Code {
            get {
                return this.open_Shop_Floor_Bin_CodeField;
            }
            set {
                this.open_Shop_Floor_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string To_Production_Bin_Code {
            get {
                return this.to_Production_Bin_CodeField;
            }
            set {
                this.to_Production_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string From_Production_Bin_Code {
            get {
                return this.from_Production_Bin_CodeField;
            }
            set {
                this.from_Production_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Adjustment_Bin_Code {
            get {
                return this.adjustment_Bin_CodeField;
            }
            set {
                this.adjustment_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Cross_Dock_Bin_Code {
            get {
                return this.cross_Dock_Bin_CodeField;
            }
            set {
                this.cross_Dock_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string To_Assembly_Bin_Code {
            get {
                return this.to_Assembly_Bin_CodeField;
            }
            set {
                this.to_Assembly_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string From_Assembly_Bin_Code {
            get {
                return this.from_Assembly_Bin_CodeField;
            }
            set {
                this.from_Assembly_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Asm_to_Order_Shpt_Bin_Code {
            get {
                return this.asm_to_Order_Shpt_Bin_CodeField;
            }
            set {
                this.asm_to_Order_Shpt_Bin_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public Special_Equipment Special_Equipment {
            get {
                return this.special_EquipmentField;
            }
            set {
                this.special_EquipmentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Special_EquipmentSpecified {
            get {
                return this.special_EquipmentFieldSpecified;
            }
            set {
                this.special_EquipmentFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public Bin_Capacity_Policy Bin_Capacity_Policy {
            get {
                return this.bin_Capacity_PolicyField;
            }
            set {
                this.bin_Capacity_PolicyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bin_Capacity_PolicySpecified {
            get {
                return this.bin_Capacity_PolicyFieldSpecified;
            }
            set {
                this.bin_Capacity_PolicyFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Allow_Breakbulk {
            get {
                return this.allow_BreakbulkField;
            }
            set {
                this.allow_BreakbulkField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_BreakbulkSpecified {
            get {
                return this.allow_BreakbulkFieldSpecified;
            }
            set {
                this.allow_BreakbulkFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Put_away_Template_Code {
            get {
                return this.put_away_Template_CodeField;
            }
            set {
                this.put_away_Template_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public bool Always_Create_Put_away_Line {
            get {
                return this.always_Create_Put_away_LineField;
            }
            set {
                this.always_Create_Put_away_LineField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Always_Create_Put_away_LineSpecified {
            get {
                return this.always_Create_Put_away_LineFieldSpecified;
            }
            set {
                this.always_Create_Put_away_LineFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Always_Create_Pick_Line {
            get {
                return this.always_Create_Pick_LineField;
            }
            set {
                this.always_Create_Pick_LineField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Always_Create_Pick_LineSpecified {
            get {
                return this.always_Create_Pick_LineFieldSpecified;
            }
            set {
                this.always_Create_Pick_LineFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Pick_According_to_FEFO {
            get {
                return this.pick_According_to_FEFOField;
            }
            set {
                this.pick_According_to_FEFOField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pick_According_to_FEFOSpecified {
            get {
                return this.pick_According_to_FEFOFieldSpecified;
            }
            set {
                this.pick_According_to_FEFOFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public enum Default_Bin_Selection {
        
        /// <comentarios/>
        _blank_,
        
        /// <comentarios/>
        Fixed_Bin,
        
        /// <comentarios/>
        Last_Used_Bin,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public enum Special_Equipment {
        
        /// <comentarios/>
        _blank_,
        
        /// <comentarios/>
        According_to_Bin,
        
        /// <comentarios/>
        According_to_SKU_Item,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public enum Bin_Capacity_Policy {
        
        /// <comentarios/>
        Never_Check_Capacity,
        
        /// <comentarios/>
        Allow_More_Than_Max_Capacity,
        
        /// <comentarios/>
        Prohibit_More_Than_Max_Cap,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public partial class DataBranch_Filter {
        
        private DataBranch_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        public DataBranch_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <comentarios/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/databranch")]
    public enum DataBranch_Fields {
        
        /// <comentarios/>
        Code,
        
        /// <comentarios/>
        Name,
        
        /// <comentarios/>
        Address,
        
        /// <comentarios/>
        Address_2,
        
        /// <comentarios/>
        City,
        
        /// <comentarios/>
        County,
        
        /// <comentarios/>
        Post_Code,
        
        /// <comentarios/>
        Country_Region_Code,
        
        /// <comentarios/>
        Contact,
        
        /// <comentarios/>
        Use_As_In_Transit,
        
        /// <comentarios/>
        Do_Not_Use_For_Tax_Calculation,
        
        /// <comentarios/>
        Tax_Area_Code,
        
        /// <comentarios/>
        Tax_Exemption_No,
        
        /// <comentarios/>
        Provincial_Tax_Area_Code,
        
        /// <comentarios/>
        Phone_No,
        
        /// <comentarios/>
        Fax_No,
        
        /// <comentarios/>
        E_Mail,
        
        /// <comentarios/>
        Home_Page,
        
        /// <comentarios/>
        Require_Receive,
        
        /// <comentarios/>
        Require_Shipment,
        
        /// <comentarios/>
        Require_Put_away,
        
        /// <comentarios/>
        Use_Put_away_Worksheet,
        
        /// <comentarios/>
        Require_Pick,
        
        /// <comentarios/>
        Bin_Mandatory,
        
        /// <comentarios/>
        Directed_Put_away_and_Pick,
        
        /// <comentarios/>
        Use_ADCS,
        
        /// <comentarios/>
        Default_Bin_Selection,
        
        /// <comentarios/>
        Outbound_Whse_Handling_Time,
        
        /// <comentarios/>
        Inbound_Whse_Handling_Time,
        
        /// <comentarios/>
        Base_Calendar_Code,
        
        /// <comentarios/>
        Customized_Calendar,
        
        /// <comentarios/>
        Use_Cross_Docking,
        
        /// <comentarios/>
        Cross_Dock_Due_Date_Calc,
        
        /// <comentarios/>
        Receipt_Bin_Code,
        
        /// <comentarios/>
        Shipment_Bin_Code,
        
        /// <comentarios/>
        Open_Shop_Floor_Bin_Code,
        
        /// <comentarios/>
        To_Production_Bin_Code,
        
        /// <comentarios/>
        From_Production_Bin_Code,
        
        /// <comentarios/>
        Adjustment_Bin_Code,
        
        /// <comentarios/>
        Cross_Dock_Bin_Code,
        
        /// <comentarios/>
        To_Assembly_Bin_Code,
        
        /// <comentarios/>
        From_Assembly_Bin_Code,
        
        /// <comentarios/>
        Asm_to_Order_Shpt_Bin_Code,
        
        /// <comentarios/>
        Special_Equipment,
        
        /// <comentarios/>
        Bin_Capacity_Policy,
        
        /// <comentarios/>
        Allow_Breakbulk,
        
        /// <comentarios/>
        Put_away_Template_Code,
        
        /// <comentarios/>
        Always_Create_Put_away_Line,
        
        /// <comentarios/>
        Always_Create_Pick_Line,
        
        /// <comentarios/>
        Pick_According_to_FEFO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch DataBranch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch[] DataBranch_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch DataBranch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataBranch[] DataBranch_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataBranch[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591