//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATX_POS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCompanyName/Page" +
            "/Clientes")]
        public string ATX_POS_WebService_Clientes_Service {
            get {
                return ((string)(this["ATX_POS_WebService_Clientes_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/DynamicsNAV90/WS/SystemService")]
        public string ATX_POS_WebService_SystemService {
            get {
                return ((string)(this["ATX_POS_WebService_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCompanyName/Code" +
            "unit/Timbrar")]
        public string ATX_POS_WebService_Timbrar {
            get {
                return ((string)(this["ATX_POS_WebService_Timbrar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCompanyName/Page" +
            "/SalesOrder")]
        public string ATX_POS_WebService_SalesOrder_Service {
            get {
                return ((string)(this["ATX_POS_WebService_SalesOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/SystemService")]
        public string ATX_POS_Webservices_SystemService {
            get {
                return ((string)(this["ATX_POS_Webservices_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCom" +
            "panyName/Page/powerbifinance")]
        public string ATX_POS_Webservices_powerbifinance_Service {
            get {
                return ((string)(this["ATX_POS_Webservices_powerbifinance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCom" +
            "panyName/Codeunit/Timbrar")]
        public string ATX_POS_Webservices_Timbrar {
            get {
                return ((string)(this["ATX_POS_Webservices_Timbrar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCom" +
            "panyName/Page/SalesOrder")]
        public string ATX_POS_Webservices_SalesOrder_Service {
            get {
                return ((string)(this["ATX_POS_Webservices_SalesOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/CRONUS%20Mexico%20S.A./Codeun" +
            "it/SalesPost80")]
        public string ATX_POS_SalesPost80_SalesPost80 {
            get {
                return ((string)(this["ATX_POS_SalesPost80_SalesPost80"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/CRONUS%20Mexico%20S.A./Page/C" +
            "lientes")]
        public string ATX_POS_SalesPost80_Clientes_Service {
            get {
                return ((string)(this["ATX_POS_SalesPost80_Clientes_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/CRONUS%20Mexico%20S.A./Page/p" +
            "owerbifinance")]
        public string ATX_POS_SalesPost80_powerbifinance_Service {
            get {
                return ((string)(this["ATX_POS_SalesPost80_powerbifinance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/CRONUS%20Mexico%20S.A./System" +
            "Service")]
        public string ATX_POS_SalesPost80_SystemService {
            get {
                return ((string)(this["ATX_POS_SalesPost80_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCom" +
            "panyName/Codeunit/TestWS")]
        public string ATX_POS_ServicesSat_TestWS {
            get {
                return ((string)(this["ATX_POS_ServicesSat_TestWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nav-ehc.sbs.atx.com.mx:9047/DynamicsNAV90/WS/ReplaceWithAPercentEncodedCom" +
            "panyName/Page/BancosSAT")]
        public string ATX_POS_ServicesSat_BancosSAT_Service {
            get {
                return ((string)(this["ATX_POS_ServicesSat_BancosSAT_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NAV-EHC\\SQLEXPRESS;Initial Catalog=NAV_POS;Integrated Security=SSPI")]
        public string NAV_POSConnectionString {
            get {
                return ((string)(this["NAV_POSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/CatalogoCuentasNa" +
            "v?tenant=gbl")]
        public string ATX_POS_AccountsFromNav_CatalogoCuentasNav_Service {
            get {
                return ((string)(this["ATX_POS_AccountsFromNav_CatalogoCuentasNav_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/BancosSAT?tenant=" +
            "gbl")]
        public string ATX_POS_CatalogoBancos_BancosSAT_Service {
            get {
                return ((string)(this["ATX_POS_CatalogoBancos_BancosSAT_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/DataBranch?tenant" +
            "=gbl")]
        public string ATX_POS_DataBranchNAV_DataBranch_Service {
            get {
                return ((string)(this["ATX_POS_DataBranchNAV_DataBranch_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/DataCompany?tenan" +
            "t=gbl")]
        public string ATX_POS_DataCompanyNAV_DataCompany_Service {
            get {
                return ((string)(this["ATX_POS_DataCompanyNAV_DataCompany_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/GeneralJourns?ten" +
            "ant=gbl")]
        public string ATX_POS_GeneralJounsNAV_GeneralJourns_Service {
            get {
                return ((string)(this["ATX_POS_GeneralJounsNAV_GeneralJourns_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/GeneralJournalPOS" +
            "?tenant=gbl")]
        public string ATX_POS_GeneralJournalNAV_GeneralJournalPOS_Service {
            get {
                return ((string)(this["ATX_POS_GeneralJournalNAV_GeneralJournalPOS_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/ItemsList?tenant=" +
            "gbl")]
        public string ATX_POS_ItemsListNAV_ItemsList_Service {
            get {
                return ((string)(this["ATX_POS_ItemsListNAV_ItemsList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/ListBranch?tenant" +
            "=gbl")]
        public string ATX_POS_ListBranchNAV_ListBranch_Service {
            get {
                return ((string)(this["ATX_POS_ListBranchNAV_ListBranch_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/MesureC?tenant=gb" +
            "l")]
        public string ATX_POS_MesureCodesFromNav_MesureC_Service {
            get {
                return ((string)(this["ATX_POS_MesureCodesFromNav_MesureC_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/PriceItems?tenant" +
            "=gbl")]
        public string ATX_POS_PriceForItems_PriceItems_Service {
            get {
                return ((string)(this["ATX_POS_PriceForItems_PriceItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/TerminalsListNAV?" +
            "tenant=gbl")]
        public string ATX_POS_TerminalsFromNAV_TerminalsListNAV_Service {
            get {
                return ((string)(this["ATX_POS_TerminalsFromNAV_TerminalsListNAV_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Codeunit/TestWS?tenant" +
            "=gbl")]
        public string ATX_POS_test2010_TestWS {
            get {
                return ((string)(this["ATX_POS_test2010_TestWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navonazure1.cloudapp.net:7047/DynamicsNAV90/WS/GBL/Page/SalesOrder?tenant" +
            "=gbl")]
        public string ATX_POS_WS_NAV_SalesOrder_Service {
            get {
                return ((string)(this["ATX_POS_WS_NAV_SalesOrder_Service"]));
            }
        }
    }
}
