//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATX_POS.ItemsListNAV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemsList_Binding", Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public partial class ItemsList_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ItemsList_Service() {
            this.Url = global::ATX_POS.Properties.Settings.Default.ATX_POS_ItemsListNAV_ItemsList_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemsList")]
        public ItemsList Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((ItemsList)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ItemsList")]
        public ItemsList ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((ItemsList)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ItemsList[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ItemsList_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ItemsList[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ItemsList_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ItemsList_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/itemslist:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/itemslist", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/itemslist", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public partial class ItemsList {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string description_2Field;
        
        private bool created_From_Nonstock_ItemField;
        
        private bool created_From_Nonstock_ItemFieldSpecified;
        
        private bool substitutes_ExistField;
        
        private bool substitutes_ExistFieldSpecified;
        
        private bool stockkeeping_Unit_ExistsField;
        
        private bool stockkeeping_Unit_ExistsFieldSpecified;
        
        private bool assembly_BOMField;
        
        private bool assembly_BOMFieldSpecified;
        
        private string production_BOM_NoField;
        
        private string routing_NoField;
        
        private string base_Unit_of_MeasureField;
        
        private string shelf_NoField;
        
        private Costing_Method costing_MethodField;
        
        private bool costing_MethodFieldSpecified;
        
        private bool cost_is_AdjustedField;
        
        private bool cost_is_AdjustedFieldSpecified;
        
        private decimal standard_CostField;
        
        private bool standard_CostFieldSpecified;
        
        private decimal unit_CostField;
        
        private bool unit_CostFieldSpecified;
        
        private decimal last_Direct_CostField;
        
        private bool last_Direct_CostFieldSpecified;
        
        private Price_Profit_Calculation price_Profit_CalculationField;
        
        private bool price_Profit_CalculationFieldSpecified;
        
        private decimal profit_PercentField;
        
        private bool profit_PercentFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private string manufacturer_CodeField;
        
        private string inventory_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private string item_Disc_GroupField;
        
        private string vendor_NoField;
        
        private string vendor_Item_NoField;
        
        private string tariff_NoField;
        
        private string search_DescriptionField;
        
        private decimal overhead_RateField;
        
        private bool overhead_RateFieldSpecified;
        
        private decimal indirect_Cost_PercentField;
        
        private bool indirect_Cost_PercentFieldSpecified;
        
        private string item_Category_CodeField;
        
        private string product_Group_CodeField;
        
        private bool blockedField;
        
        private bool blockedFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string sales_Unit_of_MeasureField;
        
        private Replenishment_System replenishment_SystemField;
        
        private bool replenishment_SystemFieldSpecified;
        
        private string purch_Unit_of_MeasureField;
        
        private string lead_Time_CalculationField;
        
        private Manufacturing_Policy manufacturing_PolicyField;
        
        private bool manufacturing_PolicyFieldSpecified;
        
        private Flushing_Method flushing_MethodField;
        
        private bool flushing_MethodFieldSpecified;
        
        private Assembly_Policy assembly_PolicyField;
        
        private bool assembly_PolicyFieldSpecified;
        
        private string item_Tracking_CodeField;
        
        private string default_Deferral_Template_CodeField;
        
        private Prevent_Negative_Inventory prevent_Negative_InventoryField;
        
        private bool prevent_Negative_InventoryFieldSpecified;
        
        /// <comentarios/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <comentarios/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        public string Description_2 {
            get {
                return this.description_2Field;
            }
            set {
                this.description_2Field = value;
            }
        }
        
        /// <comentarios/>
        public bool Created_From_Nonstock_Item {
            get {
                return this.created_From_Nonstock_ItemField;
            }
            set {
                this.created_From_Nonstock_ItemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Created_From_Nonstock_ItemSpecified {
            get {
                return this.created_From_Nonstock_ItemFieldSpecified;
            }
            set {
                this.created_From_Nonstock_ItemFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Substitutes_Exist {
            get {
                return this.substitutes_ExistField;
            }
            set {
                this.substitutes_ExistField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Substitutes_ExistSpecified {
            get {
                return this.substitutes_ExistFieldSpecified;
            }
            set {
                this.substitutes_ExistFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Stockkeeping_Unit_Exists {
            get {
                return this.stockkeeping_Unit_ExistsField;
            }
            set {
                this.stockkeeping_Unit_ExistsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Stockkeeping_Unit_ExistsSpecified {
            get {
                return this.stockkeeping_Unit_ExistsFieldSpecified;
            }
            set {
                this.stockkeeping_Unit_ExistsFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Assembly_BOM {
            get {
                return this.assembly_BOMField;
            }
            set {
                this.assembly_BOMField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Assembly_BOMSpecified {
            get {
                return this.assembly_BOMFieldSpecified;
            }
            set {
                this.assembly_BOMFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Production_BOM_No {
            get {
                return this.production_BOM_NoField;
            }
            set {
                this.production_BOM_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Routing_No {
            get {
                return this.routing_NoField;
            }
            set {
                this.routing_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Base_Unit_of_Measure {
            get {
                return this.base_Unit_of_MeasureField;
            }
            set {
                this.base_Unit_of_MeasureField = value;
            }
        }
        
        /// <comentarios/>
        public string Shelf_No {
            get {
                return this.shelf_NoField;
            }
            set {
                this.shelf_NoField = value;
            }
        }
        
        /// <comentarios/>
        public Costing_Method Costing_Method {
            get {
                return this.costing_MethodField;
            }
            set {
                this.costing_MethodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Costing_MethodSpecified {
            get {
                return this.costing_MethodFieldSpecified;
            }
            set {
                this.costing_MethodFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Cost_is_Adjusted {
            get {
                return this.cost_is_AdjustedField;
            }
            set {
                this.cost_is_AdjustedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cost_is_AdjustedSpecified {
            get {
                return this.cost_is_AdjustedFieldSpecified;
            }
            set {
                this.cost_is_AdjustedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Standard_Cost {
            get {
                return this.standard_CostField;
            }
            set {
                this.standard_CostField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Standard_CostSpecified {
            get {
                return this.standard_CostFieldSpecified;
            }
            set {
                this.standard_CostFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Unit_Cost {
            get {
                return this.unit_CostField;
            }
            set {
                this.unit_CostField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_CostSpecified {
            get {
                return this.unit_CostFieldSpecified;
            }
            set {
                this.unit_CostFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Last_Direct_Cost {
            get {
                return this.last_Direct_CostField;
            }
            set {
                this.last_Direct_CostField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Direct_CostSpecified {
            get {
                return this.last_Direct_CostFieldSpecified;
            }
            set {
                this.last_Direct_CostFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public Price_Profit_Calculation Price_Profit_Calculation {
            get {
                return this.price_Profit_CalculationField;
            }
            set {
                this.price_Profit_CalculationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Price_Profit_CalculationSpecified {
            get {
                return this.price_Profit_CalculationFieldSpecified;
            }
            set {
                this.price_Profit_CalculationFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Profit_Percent {
            get {
                return this.profit_PercentField;
            }
            set {
                this.profit_PercentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Profit_PercentSpecified {
            get {
                return this.profit_PercentFieldSpecified;
            }
            set {
                this.profit_PercentFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Manufacturer_Code {
            get {
                return this.manufacturer_CodeField;
            }
            set {
                this.manufacturer_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Inventory_Posting_Group {
            get {
                return this.inventory_Posting_GroupField;
            }
            set {
                this.inventory_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string Gen_Prod_Posting_Group {
            get {
                return this.gen_Prod_Posting_GroupField;
            }
            set {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string Item_Disc_Group {
            get {
                return this.item_Disc_GroupField;
            }
            set {
                this.item_Disc_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string Vendor_No {
            get {
                return this.vendor_NoField;
            }
            set {
                this.vendor_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Vendor_Item_No {
            get {
                return this.vendor_Item_NoField;
            }
            set {
                this.vendor_Item_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Tariff_No {
            get {
                return this.tariff_NoField;
            }
            set {
                this.tariff_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Search_Description {
            get {
                return this.search_DescriptionField;
            }
            set {
                this.search_DescriptionField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Overhead_Rate {
            get {
                return this.overhead_RateField;
            }
            set {
                this.overhead_RateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Overhead_RateSpecified {
            get {
                return this.overhead_RateFieldSpecified;
            }
            set {
                this.overhead_RateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Indirect_Cost_Percent {
            get {
                return this.indirect_Cost_PercentField;
            }
            set {
                this.indirect_Cost_PercentField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Indirect_Cost_PercentSpecified {
            get {
                return this.indirect_Cost_PercentFieldSpecified;
            }
            set {
                this.indirect_Cost_PercentFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Item_Category_Code {
            get {
                return this.item_Category_CodeField;
            }
            set {
                this.item_Category_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Product_Group_Code {
            get {
                return this.product_Group_CodeField;
            }
            set {
                this.product_Group_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public bool Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Sales_Unit_of_Measure {
            get {
                return this.sales_Unit_of_MeasureField;
            }
            set {
                this.sales_Unit_of_MeasureField = value;
            }
        }
        
        /// <comentarios/>
        public Replenishment_System Replenishment_System {
            get {
                return this.replenishment_SystemField;
            }
            set {
                this.replenishment_SystemField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Replenishment_SystemSpecified {
            get {
                return this.replenishment_SystemFieldSpecified;
            }
            set {
                this.replenishment_SystemFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Purch_Unit_of_Measure {
            get {
                return this.purch_Unit_of_MeasureField;
            }
            set {
                this.purch_Unit_of_MeasureField = value;
            }
        }
        
        /// <comentarios/>
        public string Lead_Time_Calculation {
            get {
                return this.lead_Time_CalculationField;
            }
            set {
                this.lead_Time_CalculationField = value;
            }
        }
        
        /// <comentarios/>
        public Manufacturing_Policy Manufacturing_Policy {
            get {
                return this.manufacturing_PolicyField;
            }
            set {
                this.manufacturing_PolicyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Manufacturing_PolicySpecified {
            get {
                return this.manufacturing_PolicyFieldSpecified;
            }
            set {
                this.manufacturing_PolicyFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public Flushing_Method Flushing_Method {
            get {
                return this.flushing_MethodField;
            }
            set {
                this.flushing_MethodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Flushing_MethodSpecified {
            get {
                return this.flushing_MethodFieldSpecified;
            }
            set {
                this.flushing_MethodFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public Assembly_Policy Assembly_Policy {
            get {
                return this.assembly_PolicyField;
            }
            set {
                this.assembly_PolicyField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Assembly_PolicySpecified {
            get {
                return this.assembly_PolicyFieldSpecified;
            }
            set {
                this.assembly_PolicyFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Item_Tracking_Code {
            get {
                return this.item_Tracking_CodeField;
            }
            set {
                this.item_Tracking_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Default_Deferral_Template_Code {
            get {
                return this.default_Deferral_Template_CodeField;
            }
            set {
                this.default_Deferral_Template_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public Prevent_Negative_Inventory Prevent_Negative_Inventory {
            get {
                return this.prevent_Negative_InventoryField;
            }
            set {
                this.prevent_Negative_InventoryField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prevent_Negative_InventorySpecified {
            get {
                return this.prevent_Negative_InventoryFieldSpecified;
            }
            set {
                this.prevent_Negative_InventoryFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Costing_Method {
        
        /// <comentarios/>
        FIFO,
        
        /// <comentarios/>
        LIFO,
        
        /// <comentarios/>
        Specific,
        
        /// <comentarios/>
        Average,
        
        /// <comentarios/>
        Standard,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Price_Profit_Calculation {
        
        /// <comentarios/>
        Profit_x003D_Price_Cost,
        
        /// <comentarios/>
        Price_x003D_Cost_x002B_Profit,
        
        /// <comentarios/>
        No_Relationship,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Replenishment_System {
        
        /// <comentarios/>
        Purchase,
        
        /// <comentarios/>
        Prod_Order,
        
        /// <comentarios/>
        Assembly,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Manufacturing_Policy {
        
        /// <comentarios/>
        Make_to_Stock,
        
        /// <comentarios/>
        Make_to_Order,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Flushing_Method {
        
        /// <comentarios/>
        Manual,
        
        /// <comentarios/>
        Forward,
        
        /// <comentarios/>
        Backward,
        
        /// <comentarios/>
        Pick__x002B__Forward,
        
        /// <comentarios/>
        Pick__x002B__Backward,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Assembly_Policy {
        
        /// <comentarios/>
        Assemble_to_Stock,
        
        /// <comentarios/>
        Assemble_to_Order,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum Prevent_Negative_Inventory {
        
        /// <comentarios/>
        Default,
        
        /// <comentarios/>
        No,
        
        /// <comentarios/>
        Yes,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public partial class ItemsList_Filter {
        
        private ItemsList_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        public ItemsList_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <comentarios/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemslist")]
    public enum ItemsList_Fields {
        
        /// <comentarios/>
        No,
        
        /// <comentarios/>
        Description,
        
        /// <comentarios/>
        Description_2,
        
        /// <comentarios/>
        Created_From_Nonstock_Item,
        
        /// <comentarios/>
        Substitutes_Exist,
        
        /// <comentarios/>
        Stockkeeping_Unit_Exists,
        
        /// <comentarios/>
        Assembly_BOM,
        
        /// <comentarios/>
        Production_BOM_No,
        
        /// <comentarios/>
        Routing_No,
        
        /// <comentarios/>
        Base_Unit_of_Measure,
        
        /// <comentarios/>
        Shelf_No,
        
        /// <comentarios/>
        Costing_Method,
        
        /// <comentarios/>
        Cost_is_Adjusted,
        
        /// <comentarios/>
        Standard_Cost,
        
        /// <comentarios/>
        Unit_Cost,
        
        /// <comentarios/>
        Last_Direct_Cost,
        
        /// <comentarios/>
        Price_Profit_Calculation,
        
        /// <comentarios/>
        Profit_Percent,
        
        /// <comentarios/>
        Unit_Price,
        
        /// <comentarios/>
        Manufacturer_Code,
        
        /// <comentarios/>
        Inventory_Posting_Group,
        
        /// <comentarios/>
        Gen_Prod_Posting_Group,
        
        /// <comentarios/>
        VAT_Prod_Posting_Group,
        
        /// <comentarios/>
        Item_Disc_Group,
        
        /// <comentarios/>
        Vendor_No,
        
        /// <comentarios/>
        Vendor_Item_No,
        
        /// <comentarios/>
        Tariff_No,
        
        /// <comentarios/>
        Search_Description,
        
        /// <comentarios/>
        Overhead_Rate,
        
        /// <comentarios/>
        Indirect_Cost_Percent,
        
        /// <comentarios/>
        Item_Category_Code,
        
        /// <comentarios/>
        Product_Group_Code,
        
        /// <comentarios/>
        Blocked,
        
        /// <comentarios/>
        Last_Date_Modified,
        
        /// <comentarios/>
        Sales_Unit_of_Measure,
        
        /// <comentarios/>
        Replenishment_System,
        
        /// <comentarios/>
        Purch_Unit_of_Measure,
        
        /// <comentarios/>
        Lead_Time_Calculation,
        
        /// <comentarios/>
        Manufacturing_Policy,
        
        /// <comentarios/>
        Flushing_Method,
        
        /// <comentarios/>
        Assembly_Policy,
        
        /// <comentarios/>
        Item_Tracking_Code,
        
        /// <comentarios/>
        Default_Deferral_Template_Code,
        
        /// <comentarios/>
        Prevent_Negative_Inventory,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemsList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemsList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemsList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemsList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemsList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemsList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591