//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATX_POS.AccountsFromNav {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CatalogoCuentasNav_Binding", Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public partial class CatalogoCuentasNav_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CatalogoCuentasNav_Service() {
            this.Url = global::ATX_POS.Properties.Settings.Default.ATX_POS_AccountsFromNav_CatalogoCuentasNav_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CatalogoCuentasNav")]
        public CatalogoCuentasNav Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((CatalogoCuentasNav)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CatalogoCuentasNav")]
        public CatalogoCuentasNav ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((CatalogoCuentasNav)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CatalogoCuentasNav[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] CatalogoCuentasNav_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((CatalogoCuentasNav[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CatalogoCuentasNav_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CatalogoCuentasNav_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref CatalogoCuentasNav CatalogoCuentasNav) {
            object[] results = this.Invoke("Create", new object[] {
                        CatalogoCuentasNav});
            CatalogoCuentasNav = ((CatalogoCuentasNav)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(CatalogoCuentasNav CatalogoCuentasNav) {
            this.CreateAsync(CatalogoCuentasNav, null);
        }
        
        /// <remarks/>
        public void CreateAsync(CatalogoCuentasNav CatalogoCuentasNav, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        CatalogoCuentasNav}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CatalogoCuentasNav[] CatalogoCuentasNav_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        CatalogoCuentasNav_List});
            CatalogoCuentasNav_List = ((CatalogoCuentasNav[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CatalogoCuentasNav[] CatalogoCuentasNav_List) {
            this.CreateMultipleAsync(CatalogoCuentasNav_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CatalogoCuentasNav[] CatalogoCuentasNav_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        CatalogoCuentasNav_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref CatalogoCuentasNav CatalogoCuentasNav) {
            object[] results = this.Invoke("Update", new object[] {
                        CatalogoCuentasNav});
            CatalogoCuentasNav = ((CatalogoCuentasNav)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(CatalogoCuentasNav CatalogoCuentasNav) {
            this.UpdateAsync(CatalogoCuentasNav, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(CatalogoCuentasNav CatalogoCuentasNav, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        CatalogoCuentasNav}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CatalogoCuentasNav[] CatalogoCuentasNav_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        CatalogoCuentasNav_List});
            CatalogoCuentasNav_List = ((CatalogoCuentasNav[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CatalogoCuentasNav[] CatalogoCuentasNav_List) {
            this.UpdateMultipleAsync(CatalogoCuentasNav_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CatalogoCuentasNav[] CatalogoCuentasNav_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        CatalogoCuentasNav_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/catalogocuentasnav:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public partial class CatalogoCuentasNav {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string gIFI_CodeField;
        
        private Cod_Naturaleza_Cta cod_Naturaleza_CtaField;
        
        private bool cod_Naturaleza_CtaFieldSpecified;
        
        private string sub_Account_ofField;
        
        private Income_Balance income_BalanceField;
        
        private bool income_BalanceFieldSpecified;
        
        private Account_Type account_TypeField;
        
        private bool account_TypeFieldSpecified;
        
        private bool direct_PostingField;
        
        private bool direct_PostingFieldSpecified;
        
        private string totalingField;
        
        private Gen_Posting_Type gen_Posting_TypeField;
        
        private bool gen_Posting_TypeFieldSpecified;
        
        private string gen_Bus_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private decimal net_ChangeField;
        
        private bool net_ChangeFieldSpecified;
        
        private decimal balance_at_DateField;
        
        private bool balance_at_DateFieldSpecified;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        private decimal additional_Currency_Net_ChangeField;
        
        private bool additional_Currency_Net_ChangeFieldSpecified;
        
        private decimal add_Currency_Balance_at_DateField;
        
        private bool add_Currency_Balance_at_DateFieldSpecified;
        
        private decimal additional_Currency_BalanceField;
        
        private bool additional_Currency_BalanceFieldSpecified;
        
        private string consol_Debit_AccField;
        
        private string consol_Credit_AccField;
        
        private string cost_Type_NoField;
        
        private Consol_Translation_Method consol_Translation_MethodField;
        
        private bool consol_Translation_MethodFieldSpecified;
        
        private string default_IC_Partner_G_L_Acc_NoField;
        
        private string default_Deferral_Template_CodeField;
        
        private int indentationField;
        
        private bool indentationFieldSpecified;
        
        /// <comentarios/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <comentarios/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <comentarios/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        public string GIFI_Code {
            get {
                return this.gIFI_CodeField;
            }
            set {
                this.gIFI_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public Cod_Naturaleza_Cta Cod_Naturaleza_Cta {
            get {
                return this.cod_Naturaleza_CtaField;
            }
            set {
                this.cod_Naturaleza_CtaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cod_Naturaleza_CtaSpecified {
            get {
                return this.cod_Naturaleza_CtaFieldSpecified;
            }
            set {
                this.cod_Naturaleza_CtaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Sub_Account_of {
            get {
                return this.sub_Account_ofField;
            }
            set {
                this.sub_Account_ofField = value;
            }
        }
        
        /// <comentarios/>
        public Income_Balance Income_Balance {
            get {
                return this.income_BalanceField;
            }
            set {
                this.income_BalanceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Income_BalanceSpecified {
            get {
                return this.income_BalanceFieldSpecified;
            }
            set {
                this.income_BalanceFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public Account_Type Account_Type {
            get {
                return this.account_TypeField;
            }
            set {
                this.account_TypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Account_TypeSpecified {
            get {
                return this.account_TypeFieldSpecified;
            }
            set {
                this.account_TypeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public bool Direct_Posting {
            get {
                return this.direct_PostingField;
            }
            set {
                this.direct_PostingField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Direct_PostingSpecified {
            get {
                return this.direct_PostingFieldSpecified;
            }
            set {
                this.direct_PostingFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Totaling {
            get {
                return this.totalingField;
            }
            set {
                this.totalingField = value;
            }
        }
        
        /// <comentarios/>
        public Gen_Posting_Type Gen_Posting_Type {
            get {
                return this.gen_Posting_TypeField;
            }
            set {
                this.gen_Posting_TypeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Gen_Posting_TypeSpecified {
            get {
                return this.gen_Posting_TypeFieldSpecified;
            }
            set {
                this.gen_Posting_TypeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string Gen_Prod_Posting_Group {
            get {
                return this.gen_Prod_Posting_GroupField;
            }
            set {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Net_Change {
            get {
                return this.net_ChangeField;
            }
            set {
                this.net_ChangeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Net_ChangeSpecified {
            get {
                return this.net_ChangeFieldSpecified;
            }
            set {
                this.net_ChangeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Balance_at_Date {
            get {
                return this.balance_at_DateField;
            }
            set {
                this.balance_at_DateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_at_DateSpecified {
            get {
                return this.balance_at_DateFieldSpecified;
            }
            set {
                this.balance_at_DateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Additional_Currency_Net_Change {
            get {
                return this.additional_Currency_Net_ChangeField;
            }
            set {
                this.additional_Currency_Net_ChangeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Additional_Currency_Net_ChangeSpecified {
            get {
                return this.additional_Currency_Net_ChangeFieldSpecified;
            }
            set {
                this.additional_Currency_Net_ChangeFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Add_Currency_Balance_at_Date {
            get {
                return this.add_Currency_Balance_at_DateField;
            }
            set {
                this.add_Currency_Balance_at_DateField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Add_Currency_Balance_at_DateSpecified {
            get {
                return this.add_Currency_Balance_at_DateFieldSpecified;
            }
            set {
                this.add_Currency_Balance_at_DateFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public decimal Additional_Currency_Balance {
            get {
                return this.additional_Currency_BalanceField;
            }
            set {
                this.additional_Currency_BalanceField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Additional_Currency_BalanceSpecified {
            get {
                return this.additional_Currency_BalanceFieldSpecified;
            }
            set {
                this.additional_Currency_BalanceFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Consol_Debit_Acc {
            get {
                return this.consol_Debit_AccField;
            }
            set {
                this.consol_Debit_AccField = value;
            }
        }
        
        /// <comentarios/>
        public string Consol_Credit_Acc {
            get {
                return this.consol_Credit_AccField;
            }
            set {
                this.consol_Credit_AccField = value;
            }
        }
        
        /// <comentarios/>
        public string Cost_Type_No {
            get {
                return this.cost_Type_NoField;
            }
            set {
                this.cost_Type_NoField = value;
            }
        }
        
        /// <comentarios/>
        public Consol_Translation_Method Consol_Translation_Method {
            get {
                return this.consol_Translation_MethodField;
            }
            set {
                this.consol_Translation_MethodField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Consol_Translation_MethodSpecified {
            get {
                return this.consol_Translation_MethodFieldSpecified;
            }
            set {
                this.consol_Translation_MethodFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        public string Default_IC_Partner_G_L_Acc_No {
            get {
                return this.default_IC_Partner_G_L_Acc_NoField;
            }
            set {
                this.default_IC_Partner_G_L_Acc_NoField = value;
            }
        }
        
        /// <comentarios/>
        public string Default_Deferral_Template_Code {
            get {
                return this.default_Deferral_Template_CodeField;
            }
            set {
                this.default_Deferral_Template_CodeField = value;
            }
        }
        
        /// <comentarios/>
        public int Indentation {
            get {
                return this.indentationField;
            }
            set {
                this.indentationField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndentationSpecified {
            get {
                return this.indentationFieldSpecified;
            }
            set {
                this.indentationFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public enum Cod_Naturaleza_Cta {
        
        /// <comentarios/>
        _blank_,
        
        /// <comentarios/>
        D_Deudora,
        
        /// <comentarios/>
        A_Acreedora,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public enum Income_Balance {
        
        /// <comentarios/>
        Income_Statement,
        
        /// <comentarios/>
        Balance_Sheet,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public enum Account_Type {
        
        /// <comentarios/>
        Posting,
        
        /// <comentarios/>
        Heading,
        
        /// <comentarios/>
        Total,
        
        /// <comentarios/>
        Begin_Total,
        
        /// <comentarios/>
        End_Total,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public enum Gen_Posting_Type {
        
        /// <comentarios/>
        _blank_,
        
        /// <comentarios/>
        Purchase,
        
        /// <comentarios/>
        Sale,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public enum Consol_Translation_Method {
        
        /// <comentarios/>
        Average_Rate_Manual,
        
        /// <comentarios/>
        Closing_Rate,
        
        /// <comentarios/>
        Historical_Rate,
        
        /// <comentarios/>
        Composite_Rate,
        
        /// <comentarios/>
        Equity_Rate,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public partial class CatalogoCuentasNav_Filter {
        
        private CatalogoCuentasNav_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        public CatalogoCuentasNav_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <comentarios/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/catalogocuentasnav")]
    public enum CatalogoCuentasNav_Fields {
        
        /// <comentarios/>
        No,
        
        /// <comentarios/>
        Name,
        
        /// <comentarios/>
        GIFI_Code,
        
        /// <comentarios/>
        Cod_Naturaleza_Cta,
        
        /// <comentarios/>
        Sub_Account_of,
        
        /// <comentarios/>
        Income_Balance,
        
        /// <comentarios/>
        Account_Type,
        
        /// <comentarios/>
        Direct_Posting,
        
        /// <comentarios/>
        Totaling,
        
        /// <comentarios/>
        Gen_Posting_Type,
        
        /// <comentarios/>
        Gen_Bus_Posting_Group,
        
        /// <comentarios/>
        Gen_Prod_Posting_Group,
        
        /// <comentarios/>
        VAT_Bus_Posting_Group,
        
        /// <comentarios/>
        VAT_Prod_Posting_Group,
        
        /// <comentarios/>
        Net_Change,
        
        /// <comentarios/>
        Balance_at_Date,
        
        /// <comentarios/>
        Balance,
        
        /// <comentarios/>
        Additional_Currency_Net_Change,
        
        /// <comentarios/>
        Add_Currency_Balance_at_Date,
        
        /// <comentarios/>
        Additional_Currency_Balance,
        
        /// <comentarios/>
        Consol_Debit_Acc,
        
        /// <comentarios/>
        Consol_Credit_Acc,
        
        /// <comentarios/>
        Cost_Type_No,
        
        /// <comentarios/>
        Consol_Translation_Method,
        
        /// <comentarios/>
        Default_IC_Partner_G_L_Acc_No,
        
        /// <comentarios/>
        Default_Deferral_Template_Code,
        
        /// <comentarios/>
        Indentation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav CatalogoCuentasNav {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav[] CatalogoCuentasNav_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav CatalogoCuentasNav {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoCuentasNav[] CatalogoCuentasNav_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoCuentasNav[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591